# Generated by Django 4.1.7 on 2023-05-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='status',
        ),
    ]
