# Generated by Django 4.1.7 on 2023-05-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_orderplaced_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
